# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://hybrid.pub
title: Hybrid Pedagogy Publishing
email: kris@hybridpedagogy.org
description: "Hybrid Pedagogy Publishing seeks to encourage active public discourse by publishing works that are born out of, or facilitate, community (inter)action—works that are crowdsourced or collaboratively authored, openly accessible, encourage remixing and republishing, and/or blur the lines between author and reader."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/HybridPub
  - title: github
    url: https://github.com/HybridPedagogyPublishing
